# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="A bag of emojis. 👜🛍"
REPO_LICENSE=""
REPO_TOPICS="emoji,slack,slack-emoji,zulip"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/emoji-bag.git"
REPO_WEB_URL="https://github.com/fini-net/emoji-bag"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="emoji-bag"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="false"
FLAG_CLAUDE_REVIEW="false"
FLAG_COPILOT_REVIEW="false"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "emoji"
    "slack"
    "slack-emoji"
    "zulip"
)
